apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ub6xe7gc3-nodejs
  janus-idp.io/tekton: ub6xe7gc3-nodejs
  backstage.io/kubernetes-id: ub6xe7gc3-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ub6xe7gc3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
